import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTheme } from '../../context/ThemeContext';
import { useCart } from '../../context/CartContext';
export const DeviceFrame = ({ children, activeScreen, setActiveScreen, }) => {
    const { theme, toggleTheme, viewportMode, toggleViewportMode } = useTheme();
    const { cart } = useCart();
    const isDark = theme === 'dark';
    const screens = [
        { id: 'auth', label: 'Auth & Onboarding', icon: 'lock' },
        { id: 'home', label: 'Home Feed', icon: 'home' },
        { id: 'explore', label: 'Explore & Search', icon: 'search' },
        { id: 'menu', label: 'Restaurant Menu', icon: 'restaurant_menu' },
        { id: 'cart', label: 'Cart & Checkout', icon: 'shopping_bag', badge: cart?.itemCount },
        { id: 'tracking', label: 'Live Tracking', icon: 'near_me' },
        { id: 'chat', label: 'Courier Chat', icon: 'chat' },
        { id: 'review', label: 'Rating & Feedback', icon: 'star' },
        { id: 'profile', label: 'Profile & Settings', icon: 'person' },
    ];
    return (_jsxs("div", { className: `min-h-screen transition-colors duration-300 flex flex-col items-center justify-center ${isDark ? 'bg-[#0a0a0c] text-white' : 'bg-[#f4efe9] text-[#1c1b1b]'}`, children: [_jsxs("header", { className: "w-full max-w-5xl py-3 px-4 flex flex-wrap items-center justify-between gap-3 border-b border-black/5 dark:border-white/10 mb-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-[#bb0021] dark:bg-[#ff1e38] flex items-center justify-center text-white shadow-md", children: _jsx("span", { className: "material-symbols-outlined text-[18px]", children: "restaurant" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "font-extrabold text-sm tracking-tight flex items-center gap-1.5", children: [_jsx("span", { children: "FOOD BYTE" }), _jsx("span", { className: "text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wider bg-rose-500/10 text-[#bb0021] dark:text-[#ff1e38] dark:bg-rose-500/20", children: "Consumer App (4.1)" })] }), _jsx("p", { className: "text-[11px] opacity-70", children: "10 Screen Pairs \u2022 Light & Dark Modes \u2022 Connected to Backend" })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "hidden md:flex items-center gap-1 bg-black/5 dark:bg-white/5 p-1 rounded-xl", children: screens.slice(0, 5).map(s => (_jsxs("button", { onClick: () => setActiveScreen(s.id), className: `px-2.5 py-1 rounded-lg text-xs font-semibold transition-all flex items-center gap-1 ${activeScreen === s.id
                                        ? 'bg-[#bb0021] dark:bg-[#ff1e38] text-white shadow-sm'
                                        : 'hover:bg-black/5 dark:hover:bg-white/10 opacity-80'}`, children: [_jsx("span", { children: s.label.split(' ')[0] }), s.badge ? (_jsx("span", { className: "w-4 h-4 rounded-full bg-white text-[#bb0021] text-[10px] flex items-center justify-center font-bold", children: s.badge })) : null] }, s.id))) }), _jsx("select", { value: activeScreen, onChange: e => setActiveScreen(e.target.value), className: "text-xs font-semibold px-3 py-1.5 rounded-xl border border-black/10 dark:border-white/20 bg-white/80 dark:bg-white/10 focus:outline-none", children: screens.map(s => (_jsx("option", { value: s.id, className: "text-black dark:text-white dark:bg-[#1a1a1d]", children: s.label }, s.id))) }), _jsxs("button", { onClick: toggleTheme, className: "flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold border border-black/10 dark:border-white/10 bg-white/70 dark:bg-white/10 hover:scale-105 active:scale-95 transition-all shadow-sm", title: "Toggle between Food Bites (Light) and Midnight Gastronomy (Dark)", children: [_jsx("span", { className: "material-symbols-outlined text-[16px] text-[#ff1e38]", children: isDark ? 'light_mode' : 'dark_mode' }), _jsx("span", { className: "hidden sm:inline", children: isDark ? 'Midnight Dark' : 'Food Bites Light' })] }), _jsxs("button", { onClick: toggleViewportMode, className: "flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold border border-black/10 dark:border-white/10 bg-white/70 dark:bg-white/10 hover:scale-105 active:scale-95 transition-all shadow-sm", title: "Toggle mobile device frame vs responsive full-width", children: [_jsx("span", { className: "material-symbols-outlined text-[16px]", children: viewportMode === 'mobile-frame' ? 'smartphone' : 'fit_screen' }), _jsx("span", { className: "hidden sm:inline", children: viewportMode === 'mobile-frame' ? 'Phone Frame' : 'Full Width' })] })] })] }), _jsx("main", { className: "w-full flex-1 flex items-center justify-center p-0 sm:p-4", children: viewportMode === 'mobile-frame' ? (
                /* Realistic Smartphone Bezel Container (390px x 844px) */
                _jsxs("div", { className: "relative w-full max-w-[390px] h-[854px] rounded-[3.25rem] bg-[#1a1a1e] p-[10px] shadow-[0_25px_70px_rgba(0,0,0,0.45)] ring-1 ring-white/20 overflow-hidden flex flex-col", children: [_jsx("div", { className: "absolute -left-[14px] top-28 w-[4px] h-12 bg-[#2d2d34] rounded-l-md" }), _jsx("div", { className: "absolute -left-[14px] top-44 w-[4px] h-12 bg-[#2d2d34] rounded-l-md" }), _jsx("div", { className: "absolute -right-[14px] top-36 w-[4px] h-16 bg-[#2d2d34] rounded-r-md" }), _jsxs("div", { className: `relative w-full h-full rounded-[2.6rem] overflow-hidden flex flex-col ${isDark ? 'bg-[#131315] text-[#fcf9f8]' : 'bg-[#fcf9f8] text-[#1c1b1b]'}`, children: [_jsxs("div", { className: "w-full h-11 px-7 flex items-center justify-between z-50 pointer-events-none select-none", children: [_jsx("span", { className: "text-xs font-bold tracking-tight", children: "9:41" }), _jsxs("div", { className: "w-24 h-5 rounded-full bg-black flex items-center justify-center gap-1.5 shadow-sm", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-black ring-1 ring-white/10" }), _jsx("div", { className: "w-2 h-2 rounded-full bg-[#1c1c1f]" })] }), _jsxs("div", { className: "flex items-center gap-1.5 text-xs", children: [_jsx("span", { className: "material-symbols-outlined text-[14px]", children: "signal_cellular_4_bar" }), _jsx("span", { className: "material-symbols-outlined text-[14px]", children: "wifi" }), _jsx("span", { className: "material-symbols-outlined text-[16px]", children: "battery_5_bar" })] })] }), _jsx("div", { className: "flex-1 w-full overflow-y-auto no-scrollbar relative flex flex-col", children: children }), _jsx("div", { className: "w-full h-6 flex items-center justify-center z-50 pointer-events-none bg-transparent", children: _jsx("div", { className: `w-36 h-1 rounded-full ${isDark ? 'bg-white/40' : 'bg-black/30'}` }) })] })] })) : (
                /* Full Responsive Mode */
                _jsx("div", { className: `w-full max-w-4xl min-h-[850px] rounded-3xl shadow-xl border overflow-hidden flex flex-col ${isDark ? 'bg-[#131315] text-[#fcf9f8] border-white/10' : 'bg-[#fcf9f8] text-[#1c1b1b] border-black/10'}`, children: children })) })] }));
};
//# sourceMappingURL=DeviceFrame.js.map