/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#00685f",
        "surface-container": "#f0edec",
        "on-primary-fixed": "#410005",
        "primary-fixed-dim": "#ffb3af",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1b1b",
        "outline": "#936e6c",
        "surface-container-high": "#ebe7e7",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdad7",
        "surface-dim": "#dcd9d9",
        "on-tertiary-fixed": "#00201d",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005049",
        "surface-bright": "#fcf9f8",
        "surface": "#fcf9f8",
        "tertiary-fixed": "#70f8e8",
        "secondary-fixed": "#ffdcbc",
        "secondary-fixed-dim": "#ffb86b",
        "secondary": "#895100",
        "primary-container": "#ea002c",
        "on-secondary-fixed-variant": "#683d00",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#4fdbcc",
        "on-secondary-container": "#663b00",
        "surface-container-low": "#f6f3f2",
        "on-surface": "#1c1b1b",
        "surface-container-highest": "#e5e2e1",
        "secondary-container": "#fd9d1a",
        "on-surface-variant": "#5e3f3d",
        "tertiary-container": "#008379",
        "inverse-primary": "#ffb3af",
        "on-error": "#ffffff",
        "on-tertiary-container": "#f4fffc",
        "primary": "#bb0021",
        "on-secondary": "#ffffff",
        "outline-variant": "#e8bcb9",
        "surface-tint": "#bf0022",
        "surface-variant": "#e5e2e1",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed": "#2c1700",
        "background": "#fcf9f8",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#930018",
        "inverse-surface": "#313030"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
